#ifndef _KEYBOARD_H
#define _KEYBOARD_H
#include <stdint.h>

void keyboard_isr();

// list https://wiki.osdev.org/PS/2_Keyboard
enum KEYBOARD_KEYCODE {
  KEYBOARD_ESCAPE_PRESSED = 0x01,
  KEYBOARD_BACKSPACE_PRESSED = 0xE,
  KEYBOARD_ENTER_PRESSED = 0x1C,
  KEYBOARD_LEFT_SHIFT_PRESSED = 0x2A,
  KEYBOARD_LEFT_SHIFT_RELEASED = 0xAA,
  KEYBOARD_RIGHT_SHIFT_PRESSED = 0x36,
  KEYBOARD_RIGHT_SHIFT_RELEASED = 0xB6,
  KEYBOARD_ESCAPE_RELEASED = 0x81
};

#endif
